language: python

python:
  - "2.7"
  - "3.4"

cache:
  directories:
    - $HOME/.cache/pip

# Set up our environment
env:
  DJANGO_SETTINGS_MODULE: stackdio.server.settings.testing

# So that we get a docker container
sudo: false

# Make sure our pip install works
addons:
  apt:
    packages:
      - swig

## Customize dependencies
install:
  - npm install -g bower
  - bower install
  - pip install -U pip
  - pip install -U wheel
  - pip install -U -e .[testing]

## Customize test commands
before_script:
  - pep8 stackdio/ && echo 'Finished PEP-8 Check Cleanly' || echo 'Finished PEP-8 Check With Errors'
  - pylint stackdio/ && echo 'Finished Pylint Check Cleanly' || echo 'Finished Pylint Check With Errors'
  - mkdir /home/travis/.stackdio
  - cp tests/config-travis /home/travis/.stackdio/config

script:
  - py.test --cov=stackdio stackdio
  - python manage.py build_ui

# Only build artifacts on success
after_success:
  - coveralls
  - export STACKDIO_VERSION=`python setup.py --version`
  - python setup.py sdist
  - python setup.py bdist_wheel

deploy:
  provider: releases
  api_key:
    secure: dJIj78Kl5nvtE2OpYl2I4ICEw20kLVXyr+eGOcWVV3kbU+PS6zKqOtLM+sGuVYNSbqWviRR9um6zbzjqS3S2wjFOdeStMogo19EKepSc0S97t6BkmbH0KooFuFah/YFOzLu+UBzDa3EETvgd1/988Eoojr0Ea2kZRJcvx/S0vDI=
  file:
    - dist/stackdio-server-${STACKDIO_VERSION}.tar.gz
    - dist/stackdio_server-${STACKDIO_VERSION}-py2-none-any.whl
  skip_cleanup: true
  on:
    tags: true
    repo: stackdio/stackdio
